name: Deploy To AWS

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "terraform/ecr/*"

jobs:
  create-ecr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check and Create S3 Bucket for Terraform State
        env:
          TF_STATE_BUCKET_NAME: ${{ vars.TF_STATE_BUCKET_NAME }}
        run: |
          if aws s3api head-bucket --bucket "$TF_STATE_BUCKET_NAME" 2>/dev/null; then
            echo "S3 Bucket $TF_STATE_BUCKET_NAME already exists."
          else
            echo "Creating S3 Bucket: $TF_STATE_BUCKET_NAME"
            aws s3api create-bucket --bucket "$TF_STATE_BUCKET_NAME" --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
            aws s3api put-bucket-versioning --bucket "$TF_STATE_BUCKET_NAME" --versioning-configuration Status=Enabled
            aws s3api put-bucket-encryption --bucket "$TF_STATE_BUCKET_NAME" --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SseAlgorithm":"AES256"}}]}'
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        env:
          TF_STATE_BUCKET_NAME: ${{ vars.TF_STATE_BUCKET_NAME }}
          TF_STATE_BUCKET_KEY: ${{ vars.TF_STATE_BUCKET_KEY }}
        run: |
          cd terraform/ecr
          terraform init \
            -backend-config="bucket=$TF_STATE_BUCKET_NAME" \
            -backend-config="key=$TF_STATE_BUCKET_KEY" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Apply Terraform (Create ECR if not exists)
        run: |
          cd terraform/ecr
          terraform apply -auto-approve

  build-and-push:
    needs: create-ecr
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker image
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/blogerio-img:$BUILD_NUMBER

          echo "Building Docker image: $IMAGE_URI"

          docker build -t $IMAGE_URI .

          docker push $IMAGE_URI
